### ISSUE TITLE
Proposal: CallBack function on Tick

### ISSUE THREAD

**Issue by slawekkaw** [biner88/metronome#1]
I like the Metronome package - GREAT, however I would need one additional small functionality
Suggestion - proposal:
I would like to use Metronome in my application. I would like to display the metronome icon blinking on the screen according to the current tick. For this I would need a callback function called for each TICK.

PS. I'm also waiting for a version for macOS :)

**Comment by biner88** [comment]
Very good proposal, will be implemented soon.

**Comment by biner88** [comment]
A new version has been released. If you still have issues, please reopen this issue.

**Comment by slawekkaw** [comment]
Hello Binner88,

Thank you, very good job :)
This is what I need!

I will use it in my app in the next version.

Slawek

sob., 16 mar 2024 o 05:18 biner88 ***@***.***> napisał(a):
