### ISSUE TITLE
Error:  Unable to destroy activity {app.xxxx}: java.lang.NullPointerException: Attempt to invoke virtual method 'void x5.d.c()' on a null object reference

### ISSUE THREAD

**Issue by slawekkaw** [biner88/metronome#10]
After releasing the version to the market (Android), I see a strange error reported in Crashlytics for many users:

Error:  Unable to destroy activity {app.xxxx}: java.lang.NullPointerException: Attempt to invoke virtual method 'void x5.d.c()' on a null object reference

See call-stack
![obraz](https://github.com/biner88/metronome/assets/4512206/d768d28c-c0c8-47d5-bc9e-b300c3aa2eae)

The error probably occurs when closing the application. But I can't reproduce it.
The error is ONLY visible on Android

Any suggestions?

**Comment by biner88** [comment]
As mentioned in [kijka](https://github.com/biner88/metronome/pull/7) Remove destroy from onDetachedFromEngine may be the solution, consistent with ios.
