### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel metronome_tick)

### ISSUE THREAD

**Issue by mehdisrmd** [biner88/metronome#12]
i use the example file but i have got this error

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method enableTickCallback on channel metronome)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
The following MissingPluginException was thrown while activating platform stream on channel metronome_tick:
MissingPluginException(No implementation found for method listen on channel metronome_tick)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
platform_channel.dart:676
<asynchronous suspension>

**Comment by biner88** [comment]
Web does not implement Tick.

**Comment by mehdisrmd** [comment]
> Web does not implement Tick.

I have got this error in android device and Windows

**Comment by biner88** [comment]
You can try the new version just released.
