### ISSUE TITLE
[bug] No sound with AirPods

### ISSUE THREAD

**Issue by kijka** [biner88/metronome#3]
The current audio session block doesn't allow Bluetooth stuff such as AirPods:
```
do {
    try session.setActive(true)
    try session.overrideOutputAudioPort(AVAudioSession.PortOverride.speaker)
    try session.setCategory(AVAudioSession.Category.playback)
} catch {
    print(error)
}
```

Is it possible to "broaden" it as much as possible? Thanks

**Comment by biner88** [comment]
No problem, development is in progress...

**Comment by biner88** [comment]
A new version has been released. If you still have issues, please reopen this issue.
