### ISSUE TITLE
[iOS] Configure audio session externally

### ISSUE THREAD

**Issue by kijka** [biner88/metronome#4]
Hello,

Thanks for adding the Bluetooth flag.

Is it possible to provide an additional flag in init() to skip the built-in audio session initialization block? So if the flag is true, then we can skip it and assume it's already configured and activated externally by users.

The reason is that in iOS the audio session is configured for the whole app, and sometimes I see that this plugin overrides my settings that I use https://pub.dev/packages/audio_session

In that plugin, they said it's a good practice to allow users to set audio session externally:

> You may consider asking the developer of each audio plugin you use to provide an option to not overwrite these global settings and allow them be managed externally.

**Comment by biner88** [comment]
This package was originally used in my project, so other usage scenarios were not considered. But I will take your suggestion.
