### ISSUE TITLE
[iOS] AirPods don't work

### ISSUE THREAD

**Issue by kijka** [biner88/metronome#5]
Hello again! I've tested a new version 1.1.0, and unfortunately, AirPods still don't work.

**Comment by biner88** [comment]
I tested the bluetooth headphones and they work, but I don't have AirPods, can you do a fix?

**Comment by biner88** [comment]
Please try
`try session.setCategory(AVAudioSession.Category.playback, options: AVAudioSession.CategoryOptions.allowBluetooth)`
replace
`try session.setCategory(AVAudioSession.Category.playback, options: [.defaultToSpeaker, .allowAirPlay, .allowBluetoothA2DP])`
